### ISSUE TITLE
The font is too large to exceed the display

### ISSUE THREAD

**Issue by LilyGO** [G6EJD/ESP32-e-Paper-Weather-Display#1]
hi,G6EJD.How to modify the font size. I found that the content I displayed was different from the font size of your screen display. Thank you

**Comment by G6EJD** [comment]
OK, I need to update the install instructions, please also:
Go to Sketch > Include Library... > Manage Libraries.... Then, for each library, put its name into the text field to have its metadata pulled from the internet and displayed below. Select the latest version and install it. Make sure to come back to this dialog from time to time to keep each library up to date. Also make sure that you only have one version of each of the libraries installed

ESP8266 WeatherStation by Daniel Eichhorn

The extra fonts are there.

**Comment by LilyGO** [comment]
Thank you.
