### ISSUE TITLE
platformio unable to compile

### ISSUE THREAD

**Issue by loulou4cv** [G6EJD/ESP32-e-Paper-Weather-Display#103]
Hello,

the program is working fine in ArduinoIDE, however I'm unable to compile it in platformio, do you have same problem please ?

.platformio/lib/Adafruit STMPE610_ID377/Adafruit_STMPE610.cpp:32:18: fatal error: Wire.h: No such file or directory

Thank you.

**Comment by G6EJD** [comment]
You have to include all libraries eg Wire or its equivalent in platformio, it may not be called wire and therefore all Adafruit libraries are likely to require modifications.

**Comment by loulou4cv** [comment]
Hello, 
finally found the solution. The #include <Wire.h> should work but it doesn't, you have to modify the platformio.ini to force it (no need to force other libraries). Then platformio.ini should look like :

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
upload_speed = 921600
monitor_speed = 115200

lib_deps =
  Wire@~1.0.1

Now it works.

**Comment by G6EJD** [comment]
Good to hear you solved it.
