### ISSUE TITLE
Waveshare 7.5inch doesn't compile anymore

### ISSUE THREAD

**Issue by PaulAntonDeen** [G6EJD/ESP32-e-Paper-Weather-Display#108]
The i2c file has been moved out of the adafruit library and can now be found in
Adafruit VEML6075 which depends on Adafruit BusIO
so both of those also need to be installed from the library manager to successfully compile.

**Comment by G6EJD** [comment]
Thank you, updating the relevant drivers from Adafruit does include these dependencies, it now pops up and suggest an install of these dependencies. Most users should see this. But why did Adafruit do this?
