### ISSUE TITLE
Waveshare 4.2 inch has strange <<<<<<<<head in code

### ISSUE THREAD

**Issue by PaulAntonDeen** [G6EJD/ESP32-e-Paper-Weather-Display#109]
In the BeginSleep section there is a <<<<<<<<<head and a <<<<<<<<<2134565434567 line that prevent compilation. I replaced them with the contents from the 7.5 inch version to get them to compile.

**Comment by G6EJD** [comment]
Thank you for spotting that, I think there’s a Github error as I didn’t include those erroneous lines, and just now when i corrected it, I got an error saying I’d already corrected the file!
