### ISSUE TITLE
Merge conflict committed to repo?

### ISSUE THREAD

**Issue by john--** [G6EJD/ESP32-e-Paper-Weather-Display#111]
Looks like you might have committed a merge conflict here:

https://github.com/G6EJD/ESP32-e-Paper-Weather-Display/blob/7acb28dfca717c75ce7292a070d10966038f9e43/examples/Waveshare_7_5/Waveshare_7_5.ino#L76

**Comment by G6EJD** [comment]
Interesting, it’s not showing me any conflicts, this happened a few days ago, but I can’t see why or how, I’ll correct it manually

**Comment by G6EJD** [comment]
Thanks

**Comment by john--** [comment]
Well that was fast! Thanks!
