### ISSUE TITLE
This is not exactly a problem! Cyrillic alignment does not work!

### ISSUE THREAD

**Issue by baivas** [G6EJD/ESP32-e-Paper-Weather-Display#116]
![IMG_20200913_204749](https://user-images.githubusercontent.com/71227763/93025064-a615c200-f603-11ea-88a6-3dc863d1906a.jpg)
Thanks for the idea and the excellent realization.
I allowed myself to make it look like this in Cyrillic!

This happened to me!

Greetings!

**Comment by G6EJD** [comment]
Looks good, we’ll done.

**Comment by baivas** [comment]
I made him choose from two different networks

**Comment by baivas** [comment]
but thanks for the perfect code

**Comment by baivas** [comment]
there remains the problem of alignment in different fonts

**Comment by G6EJD** [comment]
You could edit your character set to make it uniform spacing, then it will be aligned in columns.

**Comment by baivas** [comment]
https://github.com/olikraus/u8g2/wiki/fntlistall#8-pixel-height
i use these fonts

I was looking for a font editor but there is only a Mac I found

**Comment by G6EJD** [comment]
You should be able to find a font editor there are plenty around

**Comment by baivas** [comment]
you use - u8g2_font_helvB08_tf
i use this one - u8g2_font_6x13B_t_cyrillic

what is the difference

t | Transparent font,
f | The font includes up to 256 glyphs.

shouldn't the program calculate the difference between the two
