### ISSUE TITLE
WIP: Lilygo T5 2.3_2.13 board support under development

### ISSUE THREAD

**Issue by grahamwhaley** [G6EJD/ESP32-e-Paper-Weather-Display#121]
No so much an isssue, as an FYI.
I'm working on adding support for the [Lilygo TTGO 2.3 2.13"](http://www.lilygo.cn/prod_view.aspx?TypeId=50031&Id=1149&FId=t3:50031:3) board, as per detailed and supported at https://github.com/lewisxhe/TTGO-EPaper-Series#board-pins.

I took the model from the 2.9" ino file, and with very minor work have the screen up. A few things fell off the edge and are a little squashed or too large, so I'll work on the re-layout/sizing.

I'll make a pull request to add support once I'm happy it is stable.

Nice work by the way G6EJD

(Graham M7GRW)

**Comment by G6EJD** [comment]
Hi Graham, thanks for doing this, I’ll keep a look out for the pull request.  73 Dave
