### ISSUE TITLE
1.54" Display "fwidth" compilation error

### ISSUE THREAD

**Issue by wimmatthijs** [G6EJD/ESP32-e-Paper-Weather-Display#125]
The code doesn't compile, some variable is not declared?
Variable "fwidth" is not declared, function DisplayForecastWeather. 
I suppose it is meant to be offset as well as below?

**Comment by G6EJD** [comment]
Fixed that now

**Comment by wimmatthijs** [comment]
Thanks, you code faster than your shadow ;)
