### ISSUE TITLE
4.2 Version - Moon symbol on snow

### ISSUE THREAD

**Issue by bobybobybob** [G6EJD/ESP32-e-Paper-Weather-Display#130]
on 4.2 Version on snow symbol, the moon is to much up

[url=https://postimg.cc/0684KDKC][img]https://i.postimg.cc/0684KDKC/snow.jpg[/img][/url]

**Comment by bobybobybob** [comment]
https://www.bilder-upload.eu/bild-2ee4fd-1609364266.jpg.html

**Comment by bobybobybob** [comment]
other symbol + moon look very ok  https://www.bilder-upload.eu/bild-b8f9b5-1609364390.jpg.html

**Comment by G6EJD** [comment]
Try the update

**Comment by bobybobybob** [comment]
Dont know if it solve problem... after update some libaries it wont compile. much red for U8g2_for_Adafruit_GFX.cpp

**Comment by G6EJD** [comment]
They updated that library today

**Comment by bobybobybob** [comment]
OK after fresh new install of Arduino IDE + Other, compiling work and upload too.

But now

Connecting to: PowerWLAN
WiFi connected at: 192.168.1.243
Busy Timeout!
Entering 654-secs of sleep time
Awake for : 10.596-secs

only one time at 1PM it got Weaterbrodcast... other only Bussy Timeout.   Better i do no updates anymore LOL

**Comment by G6EJD** [comment]
What is the serial port /monitor saying? Are you receiving weather data?

**Comment by bobybobybob** [comment]
Dont know why... now it work again. 

+5 is not good,   +10 is nice     see photographics picture

https://www.bilder-upload.eu/bild-6830e8-1609610493.jpg.html

yes very nice and thank you for helping to find the right parameter to test and find good number. :-)

**Comment by G6EJD** [comment]
I’ve made that change now thank you.

**Comment by bobybobybob** [comment]
New Moon Problems...   

Big Symbol moon too high   and little 21 oClock symbol is moon too low?

https://www.bilder-upload.eu/bild-ee1eb5-1610568436.jpg.html

**Comment by G6EJD** [comment]
Fixed that

**Comment by bobybobybob** [comment]
big symbol is rain not snow

**Comment by G6EJD** [comment]
Try that
