### ISSUE TITLE
Issue with T5 2.9 module

### ISSUE THREAD

**Issue by Koen-wouters** [G6EJD/ESP32-e-Paper-Weather-Display#131]
Hi there, I noticed that to get your wonderful project working on the T5 module (examples Waveshare_2_9_T5 )I had to change all xEPD2_290 reference to xEPD2_290_T5, and also the common.h inclusion had to be modified (quotes instead of brackets). Otherwise my screen basically didn't do anything at all.

For the 2.4 version of the board I had to change the RST and DC pins but that was nicely mentioned in the script.

**Comment by G6EJD** [comment]
I changed the T5 code to the correct screen driver object reference, thank you.
If the files cannot find common.h that infers the library was not installed correctly.
Thank you for your help.
