### ISSUE TITLE
Support for HD screens

### ISSUE THREAD

**Issue by madnat** [G6EJD/ESP32-e-Paper-Weather-Display#132]
Hi there

Great project - thanks for sharing.  Just checking of there are any plans to support the HD versions of the Waveshare ePaper screens like this one: https://www.waveshare.com/product/displays/e-paper/epaper-1/7.8inch-e-paper-hat.htm - 1872x1404 would produce the space and resolution to have some wonderful content.

Thanks again

**Comment by G6EJD** [comment]
The support for that display is dependent on the GxEPD2 library and until he gets a display support won’t be provided, sorry.

**Comment by madnat** [comment]
Thanks for the quick reply - I do see that in release 1.2.14 of the driver added support for the 6" 1448x1072 ED060KC1 on Waveshare e-Paper IT8951 Driver HAT.  Would your application drive that display?  Thank you

**Comment by G6EJD** [comment]
Yes the application will support that screen size, albeit the display area is significantly larger and so would need to be either re-sized or the layout changed to accommodate the extra space.
