### ISSUE TITLE
Rainfall + Snow

### ISSUE THREAD

**Issue by bobybobybob** [G6EJD/ESP32-e-Paper-Weather-Display#134]
Hello,
it look like that display show only real Rainfall but not Snowfall too, what is frozen rainfall. 

Make rain + snow to the same in graph and changing rainfall to precipitation that would make information more usefull

In Serial print output i see  rain + snow seperate. Maybee it would be best to use the bigest value of that two  or rain+Snow

**Comment by G6EJD** [comment]
Some versions do, some don't depends on screen space, which version do you mean?

**Comment by bobybobybob** [comment]
i have 4.2 display   
it would fine just rain+snow as one value in that graph. in detail is not so important for me because it often depends on the temperature. For details there are the three small icons in the upper right corner. I would like to see snow in the lower right corner, if it is raining or snowing. Pure indication that just what comes down from above.

**Comment by bobybobybob** [comment]
https://www.bilder-upload.eu/bild-bb52da-1610885970.jpg.html   like example pic

**Comment by G6EJD** [comment]
Perhaps propose a solution via a pull request

**Comment by bobybobybob** [comment]
will 

snowrain[0] = WxConditions[0].Rainfall + WxConditions[0].Snowfall;

work?  I not very programable coder

**Comment by G6EJD** [comment]
Probably give it a try and see what it looks like, do they ever report both rain and snow? Otherwise the values could get too high.

**Comment by bobybobybob** [comment]
Dont know..   here i see rain and snow 

https://github.com/G6EJD/ESP32-e-Paper-Weather-Display/blob/master/src/common.h

**Comment by G6EJD** [comment]
This:
//#########################################################################################
void DisplayPrecipitationSection(int x, int y) {
  display.drawRect(x, y - 1, 167, 56, GxEPD_BLACK); // precipitation outline
  u8g2Fonts.setFont(u8g2_font_helvB10_tf);
  if (WxForecast[1].Rainfall > 0.005) { // Ignore small amounts
    drawString(x + 5, y + 15, String(WxForecast[1].Rainfall, 2) + (Units == "M" ? "mm" : "in"), LEFT); // Only display rainfall total today if > 0
    addraindrop(x + 65 - (Units == "I" ? 10 : 0), y + 16, 7);
  }
  if (WxForecast[1].Snowfall > 0.005)  // Ignore small amounts
    drawString(x + 5, y + 35, String(WxForecast[1].Snowfall, 2) + (Units == "M" ? "mm" : "in") + " * *", LEFT); // Only display snowfall total today if > 0
}

Becomes:
//#########################################################################################
void DisplayPrecipitationSection(int x, int y) {
  display.drawRect(x, y - 1, 167, 56, GxEPD_BLACK); // precipitation outline
  u8g2Fonts.setFont(u8g2_font_helvB10_tf);
  WxForecast[1].Rainfall += WxForecast[1].Snowfall;  // now the total is precipitation (rain + snow)
  if (WxForecast[1].Rainfall > 0.005) { // Ignore small amounts
    drawString(x + 5, y + 15, String(WxForecast[1].Rainfall, 2) + (Units == "M" ? "mm" : "in"), LEFT); 
    addraindrop(x + 65 - (Units == "I" ? 10 : 0), y + 16, 7);
  }
}

**Comment by bobybobybob** [comment]
Thank you. I will try it and give feedback if it is working well.

**Comment by bobybobybob** [comment]
That what look working is at 

void DrawForecastSection(int x, int y) {
++++
rain_readings[r]  = WxForecast[r].Rainfall + WxForecast[r].Snowfall;

In the serial print output data, it look like that there is only snow or rain and not both at same time. 

https://www.bilder-upload.eu/bild-c2122e-1612732790.jpg.html

**Comment by G6EJD** [comment]
Can you copy the serial port output when this occurs please, scales are different but the sum should be totalised result.

**Comment by bobybobybob** [comment]
ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1216
ho 0 tail 12 room 4
load:0x40078000,len:9720
ho 0 tail 12 room 4
load:0x40080400,len:6352
entry 0x400806b8

Connecting to: i-like-computers
WiFi connected at: 192.168.1.238

Creating object...and  Decoding weather data
 Lon: 13.51
 Lat: 51.60
Main: Snow
For0: Schnee


Icon: 13n
Temp: 0.87
Pres: 997.00
Humi: 79.00
TLow: 0.00
THig: 1.67
WSpd: 4.00
WDir: 252.00
CCov: 100
Visi: 241
Rain: 0.00
Snow: 0.89
Ctry: DE
SRis: 1612679823
SSet: 1612715225
TZon: 3600

Creating object...and  Decoding forecast data

Receiving Forecast period - 
Period-0--------------
DTim: 1612731600
Temp: 0.59
TLow: 0.30
THig: 0.59
Pres: 997.00
Humi: 88.00
For0: Snow


Icon: 13n
Desc: Schnee
CCov: 100
WSpd: 2.84
WDir: 249.00
Rain: 0.00
Snow: 3.89
Pop:  0.94
Peri: 2021-02-07 21:00:00

Period-1--------------
DTim: 1612742400
Temp: 0.08
TLow: -0.14
THig: 0.08
Pres: 998.00
Humi: 94.00
For0: Snow


Icon: 13n
Desc: Mäßiger Schnee
CCov: 100
WSpd: 1.75
WDir: 171.00
Rain: 0.00
Snow: 0.51
Pop:  0.93
Peri: 2021-02-08 00:00:00

Period-2--------------
DTim: 1612753200
Temp: -0.82
TLow: -0.93
THig: -0.82
Pres: 998.00
Humi: 96.00
For0: Clouds


Icon: 04n
Desc: Bedeckt
CCov: 100
WSpd: 1.91
WDir: 176.00
Rain: 0.00
Snow: 0.00
Pop:  0.18
Peri: 2021-02-08 03:00:00

Period-3--------------
DTim: 1612764000
Temp: -0.82
TLow: -0.83
THig: -0.82
Pres: 999.00
Humi: 97.00
For0: Clouds


Icon: 04n
Desc: Bedeckt
CCov: 100
WSpd: 1.55
WDir: 164.00
Rain: 0.00
Snow: 0.00
Pop:  0.11
Peri: 2021-02-08 06:00:00

Period-4--------------
DTim: 1612774800
Temp: 1.74
TLow: 1.74
THig: 1.74
Pres: 998.00
Humi: 85.00
For0: Clouds


Icon: 03d
Desc: Mäßig bewölkt
CCov: 42
WSpd: 1.10
WDir: 199.00
Rain: 0.00
Snow: 0.00
Pop:  0.00
Peri: 2021-02-08 09:00:00

Period-5--------------
DTim: 1612785600
Temp: 3.79
TLow: 3.79
THig: 3.79
Pres: 996.00
Humi: 73.00
For0: Clouds


Icon: 03d
Desc: Mäßig bewölkt
CCov: 33
WSpd: 0.92
WDir: 275.00
Rain: 0.00
Snow: 0.00
Pop:  0.00
Peri: 2021-02-08 12:00:00

Period-6--------------
DTim: 1612796400
Temp: 2.93
TLow: 2.93
THig: 2.93
Pres: 995.00
Humi: 79.00
For0: Clouds


Icon: 03d
Desc: Mäßig bewölkt
CCov: 37
WSpd: 0.61
WDir: 307.00
Rain: 0.00
Snow: 0.00
Pop:  0.01
Peri: 2021-02-08 15:00:00

Period-7--------------
DTim: 1612807200
Temp: -0.92
TLow: -0.92
THig: -0.92
Pres: 998.00
Humi: 96.00
For0: Clouds


Icon: 02n
Desc: Ein paar Wolken
CCov: 18
WSpd: 1.38
WDir: 150.00
Rain: 0.00
Snow: 0.00
Pop:  0.02
Peri: 2021-02-08 18:00:00

Period-8--------------
DTim: 1612818000
Temp: -1.44
TLow: -1.44
THig: -1.44
Pres: 999.00
Humi: 96.00
For0: Clouds


Icon: 04n
Desc: Überwiegend bewölkt
CCov: 60
WSpd: 0.70
WDir: 161.00
Rain: 0.00
Snow: 0.00
Pop:  0.06
Peri: 2021-02-08 21:00:00

Period-9--------------
DTim: 1612828800
Temp: -1.03
TLow: -1.03
THig: -1.03
Pres: 999.00
Humi: 98.00
For0: Snow


Icon: 13n
Desc: Mäßiger Schnee
CCov: 77
WSpd: 0.67
WDir: 224.00
Rain: 0.00
Snow: 0.28
Pop:  0.32
Peri: 2021-02-09 00:00:00

Period-10--------------
DTim: 1612839600
Temp: -0.56
TLow: -0.56
THig: -0.56
Pres: 1000.00
Humi: 95.00
For0: Snow


Icon: 13n
Desc: Mäßiger Schnee
CCov: 100
WSpd: 1.08
WDir: 167.00
Rain: 0.00
Snow: 0.41
Pop:  0.43
Peri: 2021-02-09 03:00:00

Period-11--------------
DTim: 1612850400
Temp: -1.27
TLow: -1.27
THig: -1.27
Pres: 1001.00
Humi: 97.00
For0: Snow


Icon: 13n
Desc: Mäßiger Schnee
CCov: 100
WSpd: 1.06
WDir: 209.00
Rain: 0.00
Snow: 1.16
Pop:  0.60
Peri: 2021-02-09 06:00:00

Period-12--------------
DTim: 1612861200
Temp: -0.14
TLow: -0.14
THig: -0.14
Pres: 1002.00
Humi: 98.00
For0: Snow


Icon: 13d
Desc: Mäßiger Schnee
CCov: 100
WSpd: 2.23
WDir: 202.00
Rain: 0.00
Snow: 1.43
Pop:  0.83
Peri: 2021-02-09 09:00:00

Period-13--------------
DTim: 1612872000
Temp: 1.05
TLow: 1.05
THig: 1.05
Pres: 1002.00
Humi: 95.00
For0: Snow


Icon: 13d
Desc: Mäßiger Schnee
CCov: 100
WSpd: 2.32
WDir: 253.00
Rain: 0.00
Snow: 0.81
Pop:  0.84
Peri: 2021-02-09 12:00:00

Period-14--------------
DTim: 1612882800
Temp: 1.24
TLow: 1.24
THig: 1.24
Pres: 1001.00
Humi: 95.00
For0: Snow


Icon: 13d
Desc: Mäßiger Schnee
CCov: 97
WSpd: 1.31
WDir: 202.00
Rain: 0.00
Snow: 0.25
Pop:  0.25
Peri: 2021-02-09 15:00:00

Period-15--------------
DTim: 1612893600
Temp: 0.03
TLow: 0.03
THig: 0.03
Pres: 1003.00
Humi: 98.00
For0: Clouds


Icon: 04n
Desc: Bedeckt
CCov: 98
WSpd: 0.70
WDir: 136.00
Rain: 0.00
Snow: 0.00
Pop:  0.00
Peri: 2021-02-09 18:00:00

Period-16--------------
DTim: 1612904400
Temp: -0.37
TLow: -0.37
THig: -0.37
Pres: 1003.00
Humi: 97.00
For0: Clouds


Icon: 04n
Desc: Bedeckt
CCov: 100
WSpd: 1.46
WDir: 128.00
Rain: 0.00
Snow: 0.00
Pop:  0.19
Peri: 2021-02-09 21:00:00

Period-17--------------
DTim: 1612915200
Temp: 0.40
TLow: 0.40
THig: 0.40
Pres: 1002.00
Humi: 93.00
For0: Clouds


Icon: 04n
Desc: Bedeckt
CCov: 100
WSpd: 1.06
WDir: 127.00
Rain: 0.00
Snow: 0.00
Pop:  0.00
Peri: 2021-02-10 00:00:00

Period-18--------------
DTim: 1612926000
Temp: 0.55
TLow: 0.55
THig: 0.55
Pres: 1000.00
Humi: 91.00
For0: Clouds


Icon: 04n
Desc: Bedeckt
CCov: 100
WSpd: 1.15
WDir: 133.00
Rain: 0.00
Snow: 0.00
Pop:  0.08
Peri: 2021-02-10 03:00:00

Period-19--------------
DTim: 1612936800
Temp: 0.47
TLow: 0.47
THig: 0.47
Pres: 999.00
Humi: 92.00
For0: Clouds


Icon: 04n
Desc: Bedeckt
CCov: 100
WSpd: 0.74
WDir: 58.00
Rain: 0.00
Snow: 0.00
Pop:  0.09
Peri: 2021-02-10 06:00:00

Period-20--------------
DTim: 1612947600
Temp: 2.03
TLow: 2.03
THig: 2.03
Pres: 999.00
Humi: 85.00
For0: Clouds


Icon: 04d
Desc: Bedeckt
CCov: 100
WSpd: 1.06
WDir: 323.00
Rain: 0.00
Snow: 0.00
Pop:  0.04
Peri: 2021-02-10 09:00:00

Period-21--------------
DTim: 1612958400
Temp: 2.26
TLow: 2.26
THig: 2.26
Pres: 999.00
Humi: 93.00
For0: Rain


Icon: 10d
Desc: Leichter Regen
CCov: 100
WSpd: 1.15
WDir: 262.00
Rain: 0.14
Snow: 0.00
Pop:  0.33
Peri: 2021-02-10 12:00:00

Period-22--------------
DTim: 1612969200
Temp: 0.90
TLow: 0.90
THig: 0.90
Pres: 1002.00
Humi: 98.00
For0: Rain


Icon: 10d
Desc: Leichter Regen
CCov: 100
WSpd: 1.53
WDir: 220.00
Rain: 0.24
Snow: 0.00
Pop:  1.00
Peri: 2021-02-10 15:00:00

Period-23--------------
DTim: 1612980000
Temp: -3.76
TLow: -3.76
THig: -3.76
Pres: 1008.00
Humi: 98.00
For0: Snow


Icon: 13n
Desc: Schnee
CCov: 100
WSpd: 2.51
WDir: 344.00
Rain: 0.00
Snow: 3.66
Pop:  1.00
Peri: 2021-02-10 18:00:00
13n
13n
13n
04n
Entering 955-secs of sleep time
Awake for : 4.881-secs
Starting deep-sleep period...

**Comment by G6EJD** [comment]
What did you get for the same period?

Regards

David

**Comment by bobybobybob** [comment]
((What did you get for the same period? ))    Hmm... what do you mean?

Current i am very happy with that solution. addition snow and rain in one bar graphic.

**Comment by G6EJD** [comment]
I thought from the context that you were getting the wrong result.

**Comment by bobybobybob** [comment]
After 2,5 week testing, snow+rain in one graph is working full wonderful and i will keep that on my weater epaper devices.
