### ISSUE TITLE
Problem with display.init

### ISSUE THREAD

**Issue by randompee** [G6EJD/ESP32-e-Paper-Weather-Display#137]
I tried your fine work with two E-Paper modules: Waveshare_2_13_T5 and MH-ET Live 2.9 inch B/W. The last needed class "GxEPD2_BW<GxEPD2_290_T5" instead of "GxEPD2_BW<GxEPD2_290", b.t.w.

The problem I encountered was, that the code compiled and downloaded successfully, but stopped executing after successful WiFi connection. I found out that all was well as soon as I replaced
`display.init(115200, true, 2, false)`
by
`display.init()`

**Comment by G6EJD** [comment]
Thank you for alerting me to this issue. It creates a dilemma, Waveshare changed their e-paper HAT's to favour the RPi, so the GxEPD2 author added a function to shortened the reset period to 2mS to make the new HAT's work, but then there are still some older HAT's in existence, so what I will do it edit the source code to show both options and explain what option to use in the Readme..

I've checked the 2.9" T5 code that looks correct, there are versions for each display type.
