### ISSUE TITLE
Is this item available?

### ISSUE THREAD

**Issue by JerryCloud** [G6EJD/ESP32-e-Paper-Weather-Display#138]
Is this item available? I can’t find anything related to weather icons

**Comment by G6EJD** [comment]
I’m not sure what you mean? The icons are drawn objects!

**Comment by JerryCloud** [comment]
@G6EJD This item is cool,the weather show is very nice, I want to know how to do it

**Comment by G6EJD** [comment]
Do what, the software is all here?
