### ISSUE TITLE
Alignment problem

### ISSUE THREAD

**Issue by classic-audio** [G6EJD/ESP32-e-Paper-Weather-Display#139]
Really a great project / code.
Works for me - although I have 2 minor points.
Display: 1.54 inch

1. alignment og the forecast hours on the display (3 hour forecast) - start at the mid of the screen
2. No data of the actual wind - showing 0 (zero) - I am getting data from open weather server in another application with correct data 

Where can I make these changes to have the correct data and display of data?

![IMG_3908](https://user-images.githubusercontent.com/39434972/111873700-df9fff00-8991-11eb-82f4-29f054a90d26.JPG)

**Comment by G6EJD** [comment]
You should remove these two lines:
  if (WxConditions[0].Forecast1 != "") Wx_Description += ", " + WxConditions[0].Forecast1;
  if (WxConditions[0].Forecast2 != "") Wx_Description += ", " + WxConditions[0].Forecast2;
And try replacing this line:
  drawString(x + SCREEN_WIDTH / 2, y + 3, String(ConvertUnixTime(WxForecast[index].Dt + WxConditions[0].Timezone).substring(0,5)), CENTER);

with:
  drawString(x + offset, y + 3, String(ConvertUnixTime(WxForecast[index].Dt + WxConditions[0].Timezone).substring(0,5)), CENTER);

**Comment by classic-audio** [comment]
I have a solution now - thank you very much for the fast reply.
The line:
drawString(x + offset, y + 3, String(ConvertUnixTime(WxForecast[index].Dt + WxConditions[0].Timezone).substring(0,5)), CENTER);
I made a small correction
drawString(x + offset / 2, y + 3, String(ConvertUnixTime(WxForecast[index].Dt + WxConditions[0].Timezone).substring(0,5)), CENTER);

Another small issue - at the right of the display - the boxes are missing lines at the right.
Perhaps you have a hint for that too ?


![IMG_3910](https://user-images.githubusercontent.com/39434972/111875982-dcf6d700-899c-11eb-8d9e-9d2513bab3bf.JPG)

**Comment by classic-audio** [comment]
For your info...
I also changed the text line of forecast to 2 lines - more easy to read :)

**Comment by G6EJD** [comment]
Good to hear,

try:

  display.drawRect(x, y, offset + 1, 65, GxEPD_BLACK);

to:



Regards

David

**Comment by G6EJD** [comment]
Sorry,

Keyboard error:

Try:
  display.drawRect(x, y, offset + 1, 65, GxEPD_BLACK);
to:
  display.drawRect(x, y, offset , 65, GxEPD_BLACK);

Out of interest which time zone are you in?

Regards

David

**Comment by classic-audio** [comment]
Thank you very much - fast reply and it works.

I am in Europe - Copenhagen time zone.
I live on a small Island "Venø" - central Jytland.
