### ISSUE TITLE
additionally use local data via MQTT

### ISSUE THREAD

**Issue by appi1** [G6EJD/ESP32-e-Paper-Weather-Display#144]
Hello, first of all thumbs up for this great project.
I would like to use this display in my motorhome and therefore need the weather for the location where I am.
I once implemented the GPS data as a fixed variable and it works perfectly.
String uri = "/data/2.5/" + RequestType + "? Lat =" + lat + "& lon ="
+ lon + "& APPID =" + apikey + "& mode = json & units =" + units + "& lang =" + Language;

My next step is to get the current GPS data into the sketch via MQTT. MQTT is mandatory because my router in the motorhome provides this data as a broker.
All my attempts have so far failed.
Has anyone already done that?

**Comment by G6EJD** [comment]
There’s no further development taking place for this code
