### ISSUE TITLE
Version for LilyGo 4.7 inch ESP32 Dev Board

### ISSUE THREAD

**Issue by Jozer99** [G6EJD/ESP32-e-Paper-Weather-Display#145]
I heard you had a LilyGo 4.7 inch development board.  Will the code for this version ever be posted?

**Comment by G6EJD** [comment]
There is a version on this repository, but unfortunately the very latest with over 40 bug fixes will never be released due to software piracy by individuals in Poland and Russia.

**Comment by cvanaalst** [comment]
Where can I find that version for the LilyGo T5-4.7 ? Even if it has bugs, it gives me a starting point to adapt it to my needs - really like your Weather-displays !
