### ISSUE TITLE
not declared..

### ISSUE THREAD

**Issue by yo2ldk** [G6EJD/ESP32-e-Paper-Weather-Display#149]
Hi,
nice project, thank you for that !
I have the follow error in common.h file
WxConditions was not declared in this scope...
please an advice
my best regards and 73, 
        de yo2ldk - alexander

**Comment by G6EJD** [comment]
Have you installed the repository as you would a library? You have files missing.

**Comment by yo2ldk** [comment]
No, I copied all files in the code folder
will try as library
Thank you !

**Comment by G6EJD** [comment]
Did you follow the read me?
