### ISSUE TITLE
Json?

### ISSUE THREAD

**Issue by schroepfer** [G6EJD/ESP32-e-Paper-Weather-Display#15]
Hello,
i get this errors on compiling. ArdoinoJon 6.0.1.a is installed.
Please, can you help?
BR
Juergen
PS: with ESP32_OWM_Current_Forecast_29_epaper_v7 i have the same errors!

ESP32_WU_Current_Forecast_29_epaper_v5a:351: error: 'DynamicJsonBuffer' was not declared in this scope
   DynamicJsonBuffer jsonBuffer(10*1024);
   ^
ESP32_WU_Current_Forecast_29_epaper_v5a:420: error: 'DynamicJsonBuffer' was not declared in this scope
   DynamicJsonBuffer jsonBuffer(13*1024);
   ^
exit status 1
'DynamicJsonBuffer' was not declared in this scope

**Comment by anpfeiffer56** [comment]
This version requires *** Arduino JSON v6 or above!

**Comment by schroepfer** [comment]
When you read my issue, you saw, that i wrote, that i installed ArduinoJson 6.0.1.a !

**Comment by G6EJD** [comment]
Ok downgrade the arduinojson library to v5.13.2 via sketch include manage search ‘json’ then select v 5.13.2 this will solve the problem.

**Comment by schroepfer** [comment]
Thank you! This works!

Please change your README: "This version requires *** Arduino JSON v6 or above *** ..."

**Comment by G6EJD** [comment]
Ok
