### ISSUE TITLE
Flash degrade like in ESP8266?

### ISSUE THREAD

**Issue by muelli01** [G6EJD/ESP32-e-Paper-Weather-Display#159]
The ESP8266 writes the WiFi credentials to flash every time it wakes up from sleep, unless you set
`WiFi.persistent(false);`
before
`WiFi.begin();`
Omitting that can degrade flash relatively fast.

I dumped the flash from my ESP32 and like in the ESP8266 I found the hard coded credentials stored in the flash file.
However I do not know if the ESP32 behaves the same or just simply writes it into flash once. 
But one might be better safe than sorry, I guess and add it to the WiFi routine.

**Comment by G6EJD** [comment]
According to the latest Espressif documentation:

'Starting from version 3 of this core, persistence is disabled by default and Wi-Fi does not start automatically at boot (see PR #7902).'

So no need to change anything.
