### ISSUE TITLE
Inkplate 6 / 10

### ISSUE THREAD

**Issue by mattncsu** [G6EJD/ESP32-e-Paper-Weather-Display#160]
Hello,

Is it possible to adapt your weather display code to run on the [Inkplate 6 or 10](https://github.com/e-radionicacom/Inkplate-Arduino-library/tree/master/examples/Inkplate10/Basic_Inkplate_Functionality)?  The Inkplate also uses Adafruit GFX to draw the buffer.  I'll start trying to figure it out but I'm not sure how it would be to replace GxEPD2 with the Inkplate library.

**Comment by G6EJD** [comment]
Just add:
#include "Inkplate.h"            //Include Inkplate library to the sketch
Inkplate display(INKPLATE_1BIT); // Create object on Inkplate library and set library to work in monochorme mode
remove gxepd2 references and adapt for ug8lib, should be just a few lines that change.
