### ISSUE TITLE
is Mini Grafx library still used?

### ISSUE THREAD

**Issue by skiphansen** [G6EJD/ESP32-e-Paper-Weather-Display#166]
As a learning exercise I'm writing platformio configuration files for all of the examples.  With the display I have the only example I can actually run is Waveshare_7_5_T7. 

The way I read the README only the Waveshare_7_5 projects use the GxEPD2 library and the other projects use the Mini Grafx library instead.  However I find that all of the projects seem to build fine with the GxEPD2  library.  

The getting started page for the Mini Grafx library says to include "MiniGrafx.h", but I don't find any references to it in any of the examples.

Hence my question.

73's Skip

BTW I just got my display running and it looks fantastic ... of course it was the great esthetics of your project that attracted me initially.  Good job!

**Comment by G6EJD** [comment]
Thanks Skip, I've amended the Readme accordingly
