### ISSUE TITLE
Feature Request: Support news headlines from RSS stream

### ISSUE THREAD

**Issue by m1geo** [G6EJD/ESP32-e-Paper-Weather-Display#176]
Option to supply an RSS stream and have that fill one of the empty boxes on the higher-res 7.5" screen. The BBC world topics RSS feed would be a good start.

Nice project. Thanks!
George M1GEO.

**Comment by G6EJD** [comment]
Hi George, I've added an example, you need the two files in the NEWS version, add your Lat, Lon, OWM key, news key
It displays the News item at 0,20 I have not time to position it on the screen, but it's just x, y coordinates, could display the news item on a single line somewhere.
It displays NewsItem[0] which is the most recent news item, there are 10 in total.
73 Dave

**Comment by m1geo** [comment]
You're a star, thanks! :D
