### ISSUE TITLE
Color support? (and partial refresh)

### ISSUE THREAD

**Issue by matphillips** [G6EJD/ESP32-e-Paper-Weather-Display#18]
The project looks great, I'm hovering over a "Buy" button on a 7.5" display :)
Before buying the mono display, The "color" ones, yellow or red commonly, look interesting. I know they are horribly slow, but it may be worth it depending on the results.

Is this project really to support a third color in any way, or should I just get the mono display ?

Also, does it handle partial-refresh at all?

Many thanks, I'm going to continue browsing the code trying to get a handle on it.

**Comment by G6EJD** [comment]
The driver does not support coloured displays, for those you’d need to use the GxEPD driver and modify the first section where the driver and connections are defined then add a colour to each print or draw statement as required.

Partial updates are supported by the GxEPD driver.

The mono display is very quick about 1-2 secs for an update the colour varieties are slow about 10-secs so battery life will be reduced considerably as on time is what consumes power. I get about 5-months with a 2400mAhr battery updating every hour and no updates at night after 2300.

**Comment by matphillips** [comment]
Makes sense- I didn't think about the affect the slower update would have on the battery, I recon it would be significant really. Mono it is then! I look forward to being running the code and seeing what it can do. Cheers.
