### ISSUE TITLE
GxEDP font availability

### ISSUE THREAD

**Issue by matphillips** [G6EJD/ESP32-e-Paper-Weather-Display#20]
The GxEPD2 (or GxEPD2_32) library support U8g2 font use. List of standard ones:
https://github.com/olikraus/u8g2/wiki/fntlistall

Right the way down to 4 pixels.
Not been able to check for a degree symbol at the moment, due to breaking the driver board for the screen while removing the factory installed pin headers :/

Possibly this library may provide other benefits?
I do have a (most times) working 2.9" display, and testing it with GxEDP2_32 seemed to provide very fast screen updates, perhaps three frames per second.

**Comment by matphillips** [comment]
Using your earlier work on the 7.5" code, I've refactored the 2.9" version to use GxEPD2_32 (and grew a better appreciation of the amount of work you did!)
Using just the approximate fonts, the display works but looks awful, I'll now try to switch it to U8g2 fonts and see if I can make it look as good as the original.

I also got partial updating working, and it's fast! this should have a big affect on the battery life.
I have it doing a full update on a cold start, and then partial updates waking from the timer. Every 10 wake-ups, it does a full update to the screen.

If you're amenable to it, I'll submit my version of the 2.9 code when I've solved the font handling?

**Comment by G6EJD** [comment]
Good work. For some reason the fonts in the GFX folder look particularly poor on the epaper. Waveshare won’t release any of their fonts because of licensing issues but Daniel Aichorns Thingpulse fonts are near perfect and I’ve yet to find any better, definitely san serif is needed. When I can find time I’ll have a look for some adafruit font generators and see what they look like.
I haven’t been using partial updates so-far because there are some screen life issues but I’ll watch with interest. Yes please submit your work when you can it’s all a team effort really for the good of the community. I’m currently playing with my ESP-EYE board but getting the camera to operate is a huge learning curve, that’s the great thing about this topic the amount of learning is huge and that develops the mind, which is what I like to do.

**Comment by G6EJD** [comment]
Excellent, that font works really well on an epaper and a candidate for the 7.5” display. You probably don’t need bold fonts on epaper it’s all down to choice. If you can post or email a copy.

**Comment by matphillips** [comment]
Yeah, most of those are too heavy, especially "overcast clouds" and "SSE".
I'll take a better look at the available fonts (which seems to be extensive) and set some more appropriate ones, will kick a copy of the results over tomorrow.

**Comment by matphillips** [comment]
Ok, got it to a point where I'm reasonably happy. Made loads (too many?) changes, so rather than a pull request, I'll just add the zipped file as an attachment here, that way you can cherry-pick some changes if desired. 

[battery low] text is basically a placeholder, I've not implemented the code for it (because I forgot to add a voltage divider to this board before I glued the case closed!)
[text align right, and center] not working properly at all
[pressure trend array] replaced with characters from a symbol font

Have you looked into using a single file to drive each different size of display, rather than trying to maintain multiple versions? I've a few ideas how I would go about it, but curious if you've tried, or if there's a good reason not to?

[Weather-29.ino.zip](https://github.com/G6EJD/ESP32-e-Paper-Weather-Display/files/2726767/Weather-29.ino.zip)

![img_1434](https://user-images.githubusercontent.com/1055525/50685742-4f747a00-1012-11e9-803f-6e2f9867578f.jpg)

**Comment by G6EJD** [comment]
Thanks, I’ll check it out later.

 

Regarding the center and right functions, these should work, but in your sketch, this looks wrong:

 

void drawString(int x, int y, String text, alignment align, const uint8_t* font) {

  int16_t x1, y1; //the bounds of x,y and w and h of the variable 'text' in pixels.

  uint16_t w, h;

  display.getTextBounds(text, x, y, &x1, &y1, &w, &h);

  if (align == RIGHT) {x = x - w;}

  if (align == CENTER) {x = x - w/2;}

  

  u8g2Fonts.setFont(font);

  u8g2Fonts.setCursor(x, y);

  u8g2Fonts.print(text);  

}

 

It should be:

 

void drawString(int x, int y, String text, alignment align, const uint8_t* font) {

  int16_t x1, y1; //the bounds of x,y and w and h of the variable 'text' in pixels.

  uint16_t w, h;

  u8g2Fonts.setFont(font);

  display.getTextBounds(text, x, y, &x1, &y1, &w, &h);

  if (align == RIGHT) {x = x - w;}

  if (align == CENTER) {x = x - w/2;}

  

  u8g2Fonts.setCursor(x, y);

  u8g2Fonts.print(text);  

}

 

In your version when it calls for the font text bounds it will return the width of the text string against the last sent font, so calling the printstring with 16pts, will use the results of say the last font set at maybe 6pts, therefore width will be wrong. It was working OK for the GFX fonts.

**Comment by matphillips** [comment]
Oh yeah, definitely working before! I broke it :)
Makes sense that the font should be set before the measurement is taken - that does account for the strange behaviour I was seeing!
