### ISSUE TITLE
Adding GPS issues

### ISSUE THREAD

**Issue by DanSohan** [G6EJD/ESP32-e-Paper-Weather-Display#203]
Hi - I have been attempting to add NEO GPS 6M module, to gather lat and lng to make a portable display.

What ever I do I seem to fail to get valid long and lati values back, despite receiving good values from the example text codes etc.

Is there any know reason for soft serial or TinyGPSplus not to work, or some issue with the way the esp32 sleeps?

Thank you very much for the project so far, it is excellent as a stand-alone

**Comment by G6EJD** [comment]
The first thing to check is whether you can decode the GPS sentences, presumably you can. Also presumably your getting a good lock on the satellites, usually a steady 1-sec blink on the status LED.
Next note that the timing is critical as the amount of data coming from the GPS is relatively high, so if you miss the start frame you’ll miss the whole frame. Therefore you can’t spend any appreciable timing doing other tasks before starting to receive GPS data.
As the display is relatively slow you’ll need to get the data before updating the display. 

You may need to rely on the UART buffers to enable your code to lag behind the actual data reception. So don’t use software serial or TinyGPS, and setup the serial ports for the GPS connection, so using any form of serial simulation is not going to work. There are many GPS sentences that contain lat/lon so it may be useful to try a shorter version.
