### ISSUE TITLE
Size of Weather Pictures

### ISSUE THREAD

**Issue by gopher333** [G6EJD/ESP32-e-Paper-Weather-Display#205]
First let me thank you ffor this fantastic Program! It works instantly!
Can you pls tell me the exact size of the Pictures for the weather situation top right? I want to put in own Bitmaps
Tks in advance

**Comment by G6EJD** [comment]
Top right icons? Not sure which you mean, please expand. The main icons are on a 100x100 grid, smaller types on a 50x50 grid.

On the basis that you went to conserve battery power to get maximum battery life then bitmap drawing takes a long time and so using them will reduce battery life.

**Comment by gopher333** [comment]
I mean the Pictograms of the Weather situation (Person with umbrella and so on). They are in the file Micro_Wx_Icons.h
Already had success in putting in other graphics. Using 1,54 Waveshare Display
![grafik](https://user-images.githubusercontent.com/108350292/232308243-e45cc566-2775-4c5b-9570-733c9170e413.png)

**Comment by G6EJD** [comment]
Those are 128x128 bits, I was confused because they are in the weather girl code section
