### ISSUE TITLE
Code residue?

### ISSUE THREAD

**Issue by gopher333** [G6EJD/ESP32-e-Paper-Weather-Display#206]
Dear G6EJD
System complains about Line 
if ((CurrentHour >= WakeupTime && CurrentHour <= SleepTime) **|| DebugDisplayUpdate**) 
DebugDisplayUpdate seems not to be declared (no procedure found). If I remove that part, works OK
KR gopher

**Comment by G6EJD** [comment]
Yes, a remanent of some code amendments made by others, I've removed it now, thanks for letting me know.
