### ISSUE TITLE
Sun Icon During Nighttime

### ISSUE THREAD

**Issue by Jarod96** [G6EJD/ESP32-e-Paper-Weather-Display#207]
I'm looking for a way to get rid of the sun icon during nighttime, say between sunset and sunrise, and displaying the moon in it's place instead.
is there a change that can be done easily without having to rewrite everything? how to proceed?
please enlighten me!
Thank you,
![20230421_014324](https://user-images.githubusercontent.com/131245523/233550534-82c5f31f-73f4-4a09-8c20-1422551c44fe.jpg)
EPD 5.83inch

**Comment by G6EJD** [comment]
The OWM icons are the same day and night, so I added the moon symbol. 
you could in each function add a test in from of the addsun function to only draw it when there is no moon request.

**Comment by G6EJD** [comment]
if (!IconName.endsWith("n")) addsun(..

**Comment by Jarod96** [comment]
Thanks for your helpful reply, I was struggling to figure out a way to fix that!
What is the condition that make a moon request? I've searched everywhere in the code to understand how it work but without success...
Also, can I make the sun appear only after sunrise and before sunset? since sometime the moon is up there in the sky with the sun altogether

**Comment by G6EJD** [comment]
OWM issue the icon number eg 01d or 01n hence the test checks endswith ‘n’  they calculate when it is passed sunset for your region and add ‘n’ at night
