### ISSUE TITLE
Waveshare_1_54 - Compilation error: too many arguments to function 'void addmoon(int, int, int)'

### ISSUE THREAD

**Issue by maik104** [G6EJD/ESP32-e-Paper-Weather-Display#210]
Lolin esp32

C:\Users\maik1\Documents\Arduino\ESP32-e-Paper-Weather-Display-master\examples\Waveshare_1_54\Waveshare_1_54.ino: In function 'void MostlyCloudy(int, int, bool, String)':
C:\Users\maik1\Documents\Arduino\ESP32-e-Paper-Weather-Display-master\examples\Waveshare_1_54\Waveshare_1_54.ino:414:60: error: too many arguments to function 'void addmoon(int, int, int)'
   if (IconName.endsWith("n")) addmoon(x, y, scale, IconSize);
                                                            ^
C:\Users\maik1\Documents\Arduino\ESP32-e-Paper-Weather-Display-master\examples\Waveshare_1_54\Waveshare_1_54.ino:505:6: note: declared here
 void addmoon (int x, int y, int scale) {
      ^~~~~~~
C:\Users\maik1\Documents\Arduino\ESP32-e-Paper-Weather-Display-master\examples\Waveshare_1_54\Waveshare_1_54.ino:416:59: error: too many arguments to function 'void addsun(int, int, int)'
   addsun(x - scale * 1.8, y - scale * 1.8, scale, IconSize);
                                                           ^
C:\Users\maik1\Documents\Arduino\ESP32-e-Paper-Weather-Display-master\examples\Waveshare_1_54\Waveshare_1_54.ino:366:6: note: declared here
 void addsun(int x, int y, int scale) {
      ^~~~~~
Mehrere Bibliotheken wurden für "WiFi.h" gefunden
  Benutzt: C:\Users\maik1\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.4\libraries\WiFi
  Nicht benutzt: C:\Users\maik1\Documents\Arduino\libraries\WiFi
  Nicht benutzt: C:\Users\maik1\Documents\Arduino\libraries\WiFiNINA
Mehrere Bibliotheken wurden für "WiFiClientSecure.h" gefunden
  Benutzt: C:\Users\maik1\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.4\libraries\WiFiClientSecure
  Nicht benutzt: C:\Users\maik1\Documents\Arduino\libraries\ESP8266WiFi
Mehrere Bibliotheken wurden für "SPI.h" gefunden
  Benutzt: C:\Users\maik1\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.4\libraries\SPI
  Nicht benutzt: C:\Users\maik1\Documents\Arduino\libraries\SPI
Mehrere Bibliotheken wurden für "Wire.h" gefunden
  Benutzt: C:\Users\maik1\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.4\libraries\Wire
  Nicht benutzt: C:\Users\maik1\Documents\Arduino\libraries\Wire
exit status 1

Compilation error: too many arguments to function 'void addmoon(int, int, int)'

**Comment by G6EJD** [comment]
I fixed that, I updated the central code to include the MostlyCloudy icon, but in the 1.54" version it did not need the 'iconsize' parameter.
