### ISSUE TITLE
Compilation error: too many arguments to function 'void addsun(int, int, int)'

### ISSUE THREAD

**Issue by maik104** [G6EJD/ESP32-e-Paper-Weather-Display#211]
C:\Users\maik1\Downloads\ESP32-e-Paper-Weather-Display-master\ESP32-e-Paper-Weather-Display-master\examples\Waveshare_1_54\Waveshare_1_54.ino: In function 'void MostlyCloudy(int, int, bool, String)':
C:\Users\maik1\Downloads\ESP32-e-Paper-Weather-Display-master\ESP32-e-Paper-Weather-Display-master\examples\Waveshare_1_54\Waveshare_1_54.ino:367:59: error: too many arguments to function 'void addsun(int, int, int)'
   addsun(x - scale * 1.8, y - scale * 1.8, scale, IconSize);
                                                           ^
C:\Users\maik1\Downloads\ESP32-e-Paper-Weather-Display-master\ESP32-e-Paper-Weather-Display-master\examples\Waveshare_1_54\Waveshare_1_54.ino:317:6: note: declared here
 void addsun(int x, int y, int scale) {
      ^~~~~~
Mehrere Bibliotheken wurden für "Wire.h" gefunden
  Benutzt: C:\Users\maik1\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.8\libraries\Wire
  Nicht benutzt: C:\Users\maik1\Documents\Arduino\libraries\Wire
Mehrere Bibliotheken wurden für "WiFiClientSecure.h" gefunden
  Benutzt: C:\Users\maik1\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.8\libraries\WiFiClientSecure
  Nicht benutzt: C:\Users\maik1\Documents\Arduino\libraries\ESP8266WiFi
Mehrere Bibliotheken wurden für "WiFi.h" gefunden
  Benutzt: C:\Users\maik1\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.8\libraries\WiFi
  Nicht benutzt: C:\Users\maik1\Documents\Arduino\libraries\WiFiNINA
  Nicht benutzt: C:\Users\maik1\Documents\Arduino\libraries\WiFi
Mehrere Bibliotheken wurden für "SPI.h" gefunden
  Benutzt: C:\Users\maik1\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.8\libraries\SPI
  Nicht benutzt: C:\Users\maik1\Documents\Arduino\libraries\SPI
exit status 1

Compilation error: too many arguments to function 'void addsun(int, int, int)'

**Comment by G6EJD** [comment]
Another remnant of adding a function from another code, but fixed now. Thank you for letting me know.
