### ISSUE TITLE
Can't find common.h

### ISSUE THREAD

**Issue by librarymark** [G6EJD/ESP32-e-Paper-Weather-Display#216]
No matter where I put the file, the compiler can't find common.h. 
It always says, "Compilation error: common.h: No such file or directory"

What am I missing?

**Comment by G6EJD** [comment]
Download the zip file and place in the Library folder or place common.h in the same folder as the main sketch, you will also need lang.h and forecast_record and comm_functions

**Comment by librarymark** [comment]
No joy. The file is where it belongs but I still get that error.

**Comment by G6EJD** [comment]
Well the correct place is the Library folder in accord with the structure in GitHub. You should download the zip file from GitHub, then start the IDE then go to the Sketch menu and manage libraries, then install a library from zip file and browse to the file just downloaded, then it will be correct.

**Comment by librarymark** [comment]
Once I found out where the IDE was expecting things (not where you would expect on my system for some reason) it compiled just fine - thanks!
