### ISSUE TITLE
Wemos lolin 32+epaper 1,54 v2+lipo 3,7v 2000mah battery

### ISSUE THREAD

**Issue by maik104** [G6EJD/ESP32-e-Paper-Weather-Display#226]
Hello, can you tell me how the formula with the factor:
float voltage = analogRead(36) / 4096.0 * 1.63

were?
I don't get there somehow. mfg

**Comment by G6EJD** [comment]
The ADC has a digital range of 0-4095 hence the ratio of reading/4096 this converts the readings to volts now it needs to be scaled (or if you like calibrated) based on the ADC input voltage divider which for this device is the 1.63
