### ISSUE TITLE
Wemos lolin 32+epaper 1,54 v2+lipo 3,7v 2000mah battery

### ISSUE THREAD

**Issue by maik104** [G6EJD/ESP32-e-Paper-Weather-Display#227]
hello, can you please check the code? with adc, the esp no longer wakes up, i have 2* 100k resistors on pin 35, one day it works and the next day it doesn't wake up anymore, mfg

[Waveshare_1_54.txt](https://github.com/G6EJD/ESP32-e-Paper-Weather-Display/files/12505698/Waveshare_1_54.txt)

**Comment by G6EJD** [comment]
Code is OK.
