### ISSUE TITLE
dfrobot firebeetle esp32+Waveshare_7_5_T7.ino+3,7v lipo

### ISSUE THREAD

**Issue by maik104** [G6EJD/ESP32-e-Paper-Weather-Display#228]
hello, i have this esp:
https://eckstein-shop.de/DFRobotFireBeetleESP32IOTMicrocontrollerSupportsWi-Fi26amp3BBluetoothEN
can you please check the code? with adc, the esp no longer wakes up, i have 2* 100k resistors on pin 36
, one day it works and the next day it doesn't wake up anymore, mfg
[Waveshare_7_5fire.txt](https://github.com/G6EJD/ESP32-e-Paper-Weather-Display/files/12505711/Waveshare_7_5fire.txt)

**Comment by G6EJD** [comment]
It's not the code it's the ESp32 device that is no-longer responding.

The most likely reason is the device/enclosure is being affected by static electric charge in the surrounding atmosphere, perhaps where you are it is warm and dry creating these conditions.

You can try earthing yourself before you touch the pin to wake it up, then there will be a potential difference to activate the wake up.

Problems like these can never be the software, it is always a hardware or environment issue.
