### ISSUE TITLE
External Sensor via MQTT

### ISSUE THREAD

**Issue by homuser2003** [G6EJD/ESP32-e-Paper-Weather-Display#234]
Hi,

love the project! I´m sure I (I should rather say someone more experienced than me) could add/make use of the data of an external temperature sensor that is already available in my local network publishing Temp and Hum via MQTT. 

Any hint or guidance would be apprechiated. I´d heading for the 7.5" display.

THANKS

**Comment by matthias-bs** [comment]
Hi,

You might have a look at ma fork:
https://github.com/matthias-bs/ESP32-e-Paper-Weather-Display

Regards
Matthias

**Comment by homuser2003** [comment]
Sehr geil, auch noch auf Deutsch!

Danke!
