### ISSUE TITLE
Sehr geil!

### ISSUE THREAD

**Issue by homuser2003** [G6EJD/ESP32-e-Paper-Weather-Display#235]
So, hab das mal gebaut - in einer Minimalversion zunächst.

Das Display flimmert und das ganze startet oft neu - ich vermute die Stromversorgung reicht nicht (hängt noch am USB vom Notebook).

Aber ein/zwei Fragen: Ich brauche eigentlich nur eine Page - sofern ich denn meinen einen via MQTT angebundenen Sensor mit auf der ersten Seite anzeigen könnte. Bin aber leider zu unerfahren dafür.

Sollte das mit geringem Aufwand nicht machbar sein: Wo (welche Pins am ESP32 E-Paper Driver Board) kommt der oder kommen die Touch-Sensoren dran? Ich meine verstanden zu haben es seien derer drei?

Danke!

**Comment by matthias-bs** [comment]
Please see https://github.com/matthias-bs/ESP32-e-Paper-Weather-Display/issues/5, because your questions are related to the fork [matthias-bs/ESP32-e-Paper-Weather-Display](https://github.com/matthias-bs/ESP32-e-Paper-Weather-Display).
