### ISSUE TITLE
compilation issue 

### ISSUE THREAD

**Issue by rolfeisenhut** [G6EJD/ESP32-e-Paper-Weather-Display#239]
i tried do compile the project with waveshare 2.9 inch display. 

expanded zip file and moved to examples/Waveshare_2_9 folder and started compilation from commandline with os windows 11

i always get issue 

Compiling .pio\build\esp32dev\lib06a\WiFiClientSecure\ssl_client.cpp.o
In file included from C:/00.esp32/ESP32-e-Paper-Weather-Display/examples/Waveshare_2_9/Waveshare_2_9_v4.ino:27:
.pio/libdeps/esp32dev/GxEPD2/src/GxEPD2_BW.h:29:10: fatal error: Adafruit_GFX.h: No such file or directory

seems the depended library adafruit gfx header file is not found, despite the libray is there and the file as well.

Any idea what is wrong.
following libs are used:
PACKAGES:
 - framework-arduinoespressif32 @ 2.0.9
 - tool-esptoolpy @ 1.40601.0 (4.6.1)
 - tool-mklittlefs @ 1.203.210628 (2.3)
 - tool-mkspiffs @ 2.230.0 (2.30)
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Converting Waveshare_2_9_v4.ino
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Library Manager: Installing ArduinoJson
Unpacking 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Library Manager: ArduinoJson@7.0.2 has been installed!
Library Manager: Installing Adafruit BusIO
Unpacking 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Library Manager: Adafruit BusIO@1.15.0 has been installed!
Library Manager: Installing GxEPD2
Unpacking 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Library Manager: GxEPD2@1.5.5 has been installed!
Library Manager: Resolving dependencies...
Library Manager: Installing Adafruit GFX Library
Unpacking 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Library Manager: Adafruit GFX Library@1.11.9 has been installed!
Library Manager: Resolving dependencies...
Library Manager: Installing U8g2_for_Adafruit_GFX
Unpacking 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Library Manager: U8g2_for_Adafruit_GFX@1.8.0 has been installed!
Library Manager: Resolving dependencies...
Found 38 compatible libraries
Scanning dependencies...
Dependency Graph
|-- ArduinoJson @ 7.0.2
|-- Wire @ 2.0.0
|-- HTTPClient @ 2.0.0
|-- WiFiClientSecure @ 2.0.0
|-- Adafruit BusIO @ 1.15.0
|-- GxEPD2 @ 1.5.5
|-- U8g2_for_Adafruit_GFX @ 1.8.0
|-- src
|-- examples
|-- SPI @ 2.0.0
|-- WiFi @ 2.0.0
Building in release mode

regards Rolf

**Comment by scottbob09** [comment]
Same here.   Code needs some love to be compatible with the new libraries.  But it just gets left to grow old and die

**Comment by G6EJD** [comment]
I've just taken the code and compiled it using Arduino IDE 2.3.0:
Sketch uses 929925 bytes (70%) of program storage space. Maximum is 1310720 bytes.
Global variables use 58728 bytes (17%) of dynamic memory, leaving 268952 bytes for local variables. Maximum is 327680 bytes.

It all works without any issue.

All use of libraries is up-to-date, no maintenance required.

If your using a different IDE, then it's a setup issue with it.

**Comment by scottbob09** [comment]
Interesting, since "open weather map" no longer exists.
However, the fact remains... with the code downloaded from github, it does
not compile.

**Comment by G6EJD** [comment]
I’m not sure what problems your having but the OWM service is definitely available:
https://openweathermap.org/

I think you haven’t downloaded and installed my library via the zip file and then chosen the example you need and compiled it. There are NO code issues.

I have now tried the IDE 1.18.9, 2.2.1 and the very latest 2.3.0 s d all work with no compilation errors. Your doing something very wrong.

**Comment by G6EJD** [comment]
> i tried do compile the project with waveshare 2.9 inch display.
> 
> expanded zip file and moved to examples/Waveshare_2_9 folder and started compilation from commandline with os windows 11
> 
> i always get issue
> 
> Compiling .pio\build\esp32dev\lib06a\WiFiClientSecure\ssl_client.cpp.o In file included from C:/00.esp32/ESP32-e-Paper-Weather-Display/examples/Waveshare_2_9/Waveshare_2_9_v4.ino:27: .pio/libdeps/esp32dev/GxEPD2/src/GxEPD2_BW.h:29:10: fatal error: Adafruit_GFX.h: No such file or directory
> 
> seems the depended library adafruit gfx header file is not found, despite the libray is there and the file as well.
> 
> Any idea what is wrong. following libs are used: PACKAGES:
> 
> * framework-arduinoespressif32 @ 2.0.9
> * tool-esptoolpy @ 1.40601.0 (4.6.1)
> * tool-mklittlefs @ 1.203.210628 (2.3)
> * tool-mkspiffs @ 2.230.0 (2.30)
> * toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
>   Converting Waveshare_2_9_v4.ino
>   LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
>   LDF Modes: Finder ~ chain, Compatibility ~ soft
>   Library Manager: Installing ArduinoJson
>   Unpacking 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
>   Library Manager: ArduinoJson@7.0.2 has been installed!
>   Library Manager: Installing Adafruit BusIO
>   Unpacking 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
>   Library Manager: Adafruit BusIO@1.15.0 has been installed!
>   Library Manager: Installing GxEPD2
>   Unpacking 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
>   Library Manager: GxEPD2@1.5.5 has been installed!
>   Library Manager: Resolving dependencies...
>   Library Manager: Installing Adafruit GFX Library
>   Unpacking 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
>   Library Manager: Adafruit GFX Library@1.11.9 has been installed!
>   Library Manager: Resolving dependencies...
>   Library Manager: Installing U8g2_for_Adafruit_GFX
>   Unpacking 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
>   Library Manager: U8g2_for_Adafruit_GFX@1.8.0 has been installed!
>   Library Manager: Resolving dependencies...
>   Found 38 compatible libraries
>   Scanning dependencies...
>   Dependency Graph
>   |-- ArduinoJson @ 7.0.2
>   |-- Wire @ 2.0.0
>   |-- HTTPClient @ 2.0.0
>   |-- WiFiClientSecure @ 2.0.0
>   |-- Adafruit BusIO @ 1.15.0
>   |-- GxEPD2 @ 1.5.5
>   |-- U8g2_for_Adafruit_GFX @ 1.8.0
>   |-- src
>   |-- examples
>   |-- SPI @ 2.0.0
>   |-- WiFi @ 2.0.0
>   Building in release mode
> 
> regards Rolf

How can you get an SSL library error if that’s not included in the source code? 
‘WiFiClientSecure‘

you can’t say there’s a code error when you’ve modified the code and have t read the readme about installation either.
