### ISSUE TITLE
Difference waveshare hat rev 2.2 and rev 2.3

### ISSUE THREAD

**Issue by Radiofreund** [G6EJD/ESP32-e-Paper-Weather-Display#241]
I have a problem with a new waveshare epaper hat revision 2.3.
I have been running this project for a year with a 7.5 waveshare epaer b/w and a hat rev.2.2 without any problems.
As I like the project so much, I wanted to build another one for my office.
I ordered an epaper 7.5 b/w with has from waveshare.
I noticed that the hat is now 9-pin and no longer 8-pin.
At first I thought, no problem, I don't need the new "pwr" connection..., but the panel didn't work. Everything is ok on the old esp32 and the old one.
I've been fiddling around for 1 week now, I read on waveshare that: 
Different versions:
RST pin now is for reset control, and not for power on/off.
Add a new PWR pin for power on/off.

https://www.waveshare.com/wiki/E-Paper_Driver_HAT

Unfortunately, the whole thing overwhelms me.
Does anyone have any advice for me or new wiring?

Many thanks for any tips.
RK

**Comment by G6EJD** [comment]
VCC - as Now
GND - as now
DIN/MOSI - as now
CLK - as now
CS - as now
DC - as now
RST - as now
BUSY - as now
PWR - connect to +3.3v

so just add 3.3v connection to PWR to turn the Panel on, or ground it to turn off, or use a spare GPIO pin set high for on, or low for off. Turning off the panels saves some power, but not much.
