### ISSUE TITLE
Power not displayed

### ISSUE THREAD

**Issue by Stebe242** [G6EJD/ESP32-e-Paper-Weather-Display#244]
My Power is not displayed as in the example

![grafik](https://github.com/G6EJD/ESP32-e-Paper-Weather-Display/assets/122525247/267e8852-55a2-43cc-9dd0-3aaa3fba5600)

I use the waveshare e-paper esp32 driver board and an TP4056

**Comment by G6EJD** [comment]
Pleased to hear you have the display sorted.

you won’t get a voltage reading unless your development board has a voltage monitor fitted. Or maybe is used another pin, some do. If not you’d need to fit an external voltage divider that feeds a suitable pin to attach an ADC channel to, just change the readAnalog line and the pin number
