### ISSUE TITLE
Code suddenly throwing errors when compiled again, although currently successfully running on an ESP32 

### ISSUE THREAD

**Issue by nero-on-fire** [G6EJD/ESP32-e-Paper-Weather-Display#259]
I have an ESP32 currently running the code and displaying everything perfectly fine on a Waveshare 3.7 display.

Now I wanted to upload the code to a second (identical) ESP32, but I get several error codes with the same code, the cause of which I cannot interpret exactly.

The code has not been changed at all between the uploads, the only change was pending updates to the libraries, which I do regularly.

Can anyone give me a hint based on the error codes as to where the problem lies with the code/libraries?

Thank you very much!

**Error Codes:**

> `F:\Lighthouse_NEW\ESP32\Weatherstation_Landscape\ESP32-e-Paper-Weather-Display-MR\ESP32-e-Paper-Weather-Display-MR.ino: In function 'uint8_t StartWiFi()':
> F:\Lighthouse_NEW\ESP32\Weatherstation_Landscape\ESP32-e-Paper-Weather-Display-MR\ESP32-e-Paper-Weather-Display-MR.ino:531:8: error: 'class WiFiClass' has no member named 'setAutoConnect'; did you mean 'setAutoReconnect'?
>   531 |   WiFi.setAutoConnect(true);
>       |        ^~~~~~~~~~~~~~
>       |        setAutoReconnect
> F:\Lighthouse_NEW\ESP32\Weatherstation_Landscape\ESP32-e-Paper-Weather-Display-MR\ESP32-e-Paper-Weather-Display-MR.ino: In function 'void DrawBattery(int, int)':
> F:\Lighthouse_NEW\ESP32\Weatherstation_Landscape\ESP32-e-Paper-Weather-Display-MR\ESP32-e-Paper-Weather-Display-MR.ino:916:3: error: 'adc_power_acquire' was not declared in this scope
>   916 |   adc_power_acquire();
>       |   ^~~~~~~~~~~~~~~~~
> F:\Lighthouse_NEW\ESP32\Weatherstation_Landscape\ESP32-e-Paper-Weather-Display-MR\ESP32-e-Paper-Weather-Display-MR.ino:918:3: error: 'adc_power_release' was not declared in this scope
>   918 |   adc_power_release();
>       |   ^~~~~~~~~~~~~~~~~
> F:\Lighthouse_NEW\ESP32\Weatherstation_Landscape\ESP32-e-Paper-Weather-Display-MR\ESP32-e-Paper-Weather-Display-MR.ino:928:51: error: 'ADC_ATTEN_11db' was not declared in this scope; did you mean 'ADC_ATTEN_DB_6'?
>   928 |   val_type = esp_adc_cal_characterize(ADC_UNIT_1, ADC_ATTEN_11db, ADC_WIDTH_BIT_12, 1100, &adc_chars);
>       |                                                   ^~~~~~~~~~~~~~
>       |                                                   ADC_ATTEN_DB_6
> 
> exit status 1
> 
> Compilation error: 'class WiFiClass' has no member named 'setAutoConnect'; did you mean 'setAutoReconnect'?`

**Comment by G6EJD** [comment]
Yes the libraries have just been updated, but easily fixed:
Just change setAutoconnect to setAutoReconnect as suggested in the error line. Omitting true.

Delete the line auto power acquire. And the same for release. 

And change 11db to DB_6

you may yet receive other errors!

**Comment by nero-on-fire** [comment]
Okay, I thought the issue with the libraries was a bigger problem that couldn't be solved so easily.

I got it fixed after a few tries with your advice. I never thought that the solution to the problem would be to simply delete the lines with the errors.

Just a little hint from my side: The line 531 "WiFi.setAutoReconnect(true);" needs the "true", omitting it results in an error.

Thanks for the fast help! And another 'thank you' for such a wonderful, well kept and well documented project!

**Comment by G6EJD** [comment]
Good to hear you’ve got it fixed, I’ll update them all.
