### ISSUE TITLE
No 3 hrs forecast

### ISSUE THREAD

**Issue by austinroolon** [G6EJD/ESP32-e-Paper-Weather-Display#265]
Display:
2.9 WeActStudio Epaper, 
Sketch:
Waveshare_2_9_v4.ino](https://github.com/G6EJD/ESP32-e-Paper-Weather-Display/blob/master/Waveshare_2_9_v4.ino 
Problems:
1. I have only daily forecast (today+2 days).
I prefer 3 hrs forecast, but I can`t find how to do it (like on pictures). Something change in sketch? 
2. During updating the data display turns whole black, than it is flickering, then turns white blank(white) and then inverted picture then correct (white background, white letters). 
3. Direction of the wind. Should show direction where FROM is the wind.

Thank you for your effort!
BTW it is important to change ePaper display definition when we use 2.9 WeActStudio ePaper display
// 2.9'' EPD Module
//GxEPD2_BW<GxEPD2_290_BS
//GxEPD2_3C<GxEPD2_290_C90c

**Comment by G6EJD** [comment]
There are many 2.9” displays on the market, so the correct type needs to be selected from the GxEzPD2 library.

OWM only publish 3-hour forecast data , look at 
Void DisplayWeather()
In that function is a count to receive the forecasts 0, 1 and 2 so you could increase the 2 to 3

**Comment by austinroolon** [comment]
In my shetch in Void DisplayWeather() section I have:
int Forecast = 2, Dposition = 0;  (no changes)
any on my display I have DAILY forecast only. At bottom line there are 4 fields:
SUN MON TUE and the big one with Moon and sunrise/sunset time.
but 
I have no idea how change into:
NOW/ NOW+3hrs / NOW+6hrs

**Comment by austinroolon** [comment]
I used Waveshare_2_9_T5 instead of before used Waveshare_2_9_v4 and it is ok
Waveshare_2_9_v4 is a daily update sketch
Waveshare_2_9_T5 is 3-hrs update sketch.
Solved
