### ISSUE TITLE
Compilation error: 'obtain_wx_data' cannot be used as a function

### ISSUE THREAD

**Issue by robstermn** [G6EJD/ESP32-e-Paper-Weather-Display#268]
I'm getting the following error when trying to verify via Arduino ide,Waveshare 2.9 

Compilation error: 'obtain_wx_data' cannot be used as a function

**Comment by G6EJD** [comment]
Is the supporting library installed or updated?

**Comment by robstermn** [comment]
Yes, when I tried to complie in VS_CODE it seemed to work fine?  I'll try testing again with Ardunio this week.

**Comment by G6EJD** [comment]
That error suggests the function is not defined by the common.h file in the library
