### ISSUE TITLE
defined twice

### ISSUE THREAD

**Issue by schroepfer** [G6EJD/ESP32-e-Paper-Weather-Display#3]
"api.wunderground.com" is defined twice, in the main and in credential.h

_ESP32-e-Paper-Weather-Display:90: error: redefinition of 'const char* host'
 const char* host = "api.wunderground.com";
             ^
In file included from /Users/Juergen-S/Desktop/ESP32-e-Paper-Weather-Display/ESP32-e-Paper-Weather-Display.ino:22:0:
sketch/credentials.h:13:13: note: 'const char* host' previously defined here
 const char* host    = "api.wunderground.com";_

**Comment by G6EJD** [comment]
Removed duplicate
