### ISSUE TITLE
You forgot a curly brace

### ISSUE THREAD

**Issue by schroepfer** [G6EJD/ESP32-e-Paper-Weather-Display#71]
Hello,
You forgot a curly brace in your library:

C:\Dummy\Arduino\portable\sketchbook\libraries\ESP32-e-Paper-Weather-Display-master\src/lang_gr.h:73:78: error: expected '}' before ';' token

 const char* weekday_D[] =  { "So.", "Mo.", "Di.", "Mi.", "Do.", "Fr.", "Sa." ;

**Comment by G6EJD** [comment]
Thank you I’ll update that as soon as I can this morning.

**Comment by schroepfer** [comment]
I think, this is not realy a BIG problem!   ;-)

**Comment by G6EJD** [comment]
Corrected now.
