### ISSUE TITLE
Formatting of the wind direction and speed on 1.54-epaper

### ISSUE THREAD

**Issue by schroepfer** [G6EJD/ESP32-e-Paper-Weather-Display#74]
The formatting of the wind direction and speed isn't realy ok:

<a href="https://www.bilder-upload.eu/bild-df0be4-1566544594.jpg.html" target="_blank"><img src="https://www.bilder-upload.eu/thumb/df0be4-1566544594.jpg" border="1" alt="Bilder-Upload.eu - share DEINE Bilder" /></a>

**Comment by G6EJD** [comment]
It’s how it comes from Open Weather Map, please raise an issue with them. Or write your own code.

**Comment by G6EJD** [comment]
Hmm...
