### ISSUE TITLE
Typo in Waveshare_7_5.ino

### ISSUE THREAD

**Issue by vemeT5ak** [G6EJD/ESP32-e-Paper-Weather-Display#77]
Hello, I've been hunting and pecking around and found a typo in Waveshare_7_5.ino. The tri color displays will not work. Line 60 is missing a couple of c's. 

Consider changing GxEPD2_3C<GxEPD2_750, GxEPD2_750:: to GxEPD2_3C<GxEPD2_750c, GxEPD2_750c::

This was found by looking at the GxEPD2_example  line 137

Enjoy your evening

**Comment by G6EJD** [comment]
Thanks, I’ve updated the code
