### ISSUE TITLE
ESP8266 WeatherStation' by Daniel Eichhorn library

### ISSUE THREAD

**Issue by lrtal** [G6EJD/ESP32-e-Paper-Weather-Display#8]
hello
cant find the ESP8266 WeatherStation' by Daniel Eichhorn library

**Comment by wilhelmzeuschner** [comment]
https://github.com/ThingPulse/esp8266-weather-station

**Comment by G6EJD** [comment]
Thank you for including the link and you have to follow the Thingpulse instructions for library installation as there are a few cross references that are not obvious.
