### ISSUE TITLE
Version String Missing Terminating Character

### ISSUE THREAD

**Issue by capnmattttt** [G6EJD/ESP32-e-Paper-Weather-Display#84]
Line 75 of Waveshare_7_5 Example missing "

IS:

//################  VERSION  ###########################################
String version = "16.7;     // Programme version, see change log at end
//################ VARIABLES ###########################################

SHOULD BE:

//################  VERSION  ###########################################
String version = "16.7";     // Programme version, see change log at end
//################ VARIABLES ###########################################

FYI, love the project! Thank you.

--Matt

**Comment by G6EJD** [comment]
Thank you, I corrected the omission. Good to hear your enjoying the project.
