### ISSUE TITLE
Support for 12.48“ display planned?

### ISSUE THREAD

**Issue by AWSW2017** [G6EJD/ESP32-e-Paper-Weather-Display#87]
Hello 👋 

Do you plan to support the 12.48” ePaper displays from Waveshare too?

https://www.waveshare.com/product/displays/e-paper/12.48inch-e-paper-module.htm
https://www.waveshare.com/product/displays/e-paper/12.48inch-e-paper-b.htm
https://www.waveshare.com/product/displays/e-paper/12.48inch-e-paper.htm

Thanks for your reply in advance. 😊

Kind regards 
AWSW

**Comment by G6EJD** [comment]
It’s not me it’s the author of GxEPD2 driver library
